In [239]:
import numpy as np
import pandas as pd

In [240]:
df = pd.read_csv('Bengaluru_House_Data.csv')

In [241]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [242]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [243]:
df.tail()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.0

In [244]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [245]:
df.duplicated().sum()

np.int64(530)

In [246]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [247]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [248]:
df['area_type']

0        Super built-up  Area
1                  Plot  Area
2              Built-up  Area
3        Super built-up  Area
4        Super built-up  Area
                 ...
13315          Built-up  Area
13316    Super built-up  Area
13317          Built-up  Area
13318    Super built-up  Area
13319    Super built-up  Area
Name: area_type, Length: 13320, dtype: object

In [249]:
df['area_type'].value_counts()

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64

In [250]:
df['area_type'].unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [251]:
df['area_type'] = df['area_type'].str.replace('  ', ' ')

In [252]:
df['area_type'].unique()

array(['Super built-up Area', 'Plot Area', 'Built-up Area', 'Carpet Area'],
      dtype=object)

In [253]:
def classify(x):
    string = ''
    for i in range(0, len(x)):
        if ((i == 0) and (65 <= ord(x[i]) <= 90)) or (((ord(x[i - 1]) == 32) or (ord(x[i - 1]) == 45)) and (65 <= ord(x[i]) <= 90)):
            string += x[i]
        elif ((i == 0) and (97 <= ord(x[i]) <= 122)) or (((ord(x[i - 1]) == 32) or (ord(x[i - 1]) == 45)) and (97 <= ord(x[i]) <= 122)):
            string += chr(ord(x[i]) - 32)
        else:
            string += x[i]
    return string

In [254]:
df['area_type'] = df['area_type'].apply(classify)

In [255]:
df['area_type'].unique()

array(['Super Built-Up Area', 'Plot Area', 'Built-Up Area', 'Carpet Area'],
      dtype=object)

In [256]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [257]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [258]:
df['availability']

0               19-Dec
1        Ready To Move
2        Ready To Move
3        Ready To Move
4        Ready To Move
             ...
13315    Ready To Move
13316    Ready To Move
13317    Ready To Move
13318           18-Jun
13319    Ready To Move
Name: availability, Length: 13320, dtype: object

In [259]:
df['availability'].unique()

array(['19-Dec', 'Ready To Move', '18-May', '18-Feb', '18-Nov', '20-Dec',
       '17-Oct', '21-Dec', '19-Sep', '20-Sep', '18-Mar', '20-Feb',
       '18-Apr', '20-Aug', '18-Oct', '19-Mar', '17-Sep', '18-Dec',
       '17-Aug', '19-Apr', '18-Jun', '22-Dec', '22-Jan', '18-Aug',
       '19-Jan', '17-Jul', '18-Jul', '21-Jun', '20-May', '19-Aug',
       '18-Sep', '17-May', '17-Jun', '21-May', '18-Jan', '20-Mar',
       '17-Dec', '16-Mar', '19-Jun', '22-Jun', '19-Jul', '21-Feb',
       'Immediate Possession', '19-May', '17-Nov', '20-Oct', '20-Jun',
       '19-Feb', '21-Oct', '21-Jan', '17-Mar', '17-Apr', '22-May',
       '19-Oct', '21-Jul', '21-Nov', '21-Mar', '16-Dec', '22-Mar',
       '20-Jan', '21-Sep', '21-Aug', '14-Nov', '19-Nov', '15-Nov',
       '16-Jul', '15-Jun', '17-Feb', '20-Nov', '20-Jul', '16-Sep',
       '15-Oct', '15-Dec', '16-Oct', '22-Nov', '15-Aug', '17-Jan',
       '16-Nov', '20-Apr', '16-Jan', '14-Jul'], dtype=object)

In [260]:
def classify1(x):
    if 'Ready To Move' in x:
        return 'Ready'
    elif 'Immediate Possession' in x:
        return 'Ready'
    else:
        return 'Under Construction'

In [261]:
df['availability'] = df['availability'].apply(classify1)

In [262]:
df['availability'].unique()

array(['Under Construction', 'Ready'], dtype=object)

In [263]:
df['availability'].value_counts()

availability
Ready                 10597
Under Construction     2723
Name: count, dtype: int64

In [264]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [265]:
df['location']

0        Electronic City Phase II
1                Chikka Tirupathi
2                     Uttarahalli
3              Lingadheeranahalli
4                        Kothanur
                   ...
13315                  Whitefield
13316               Richards Town
13317       Raja Rajeshwari Nagar
13318             Padmanabhanagar
13319                Doddathoguru
Name: location, Length: 13320, dtype: object

In [266]:
df['location'].unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12th cross srinivas nagar banshankari 3rd stage',
       'Havanur extension', 'Abshot Layout'], dtype=object)

In [267]:
df['location'] = df['location'].astype('str')

In [268]:
def classify2(x):
    if 'JP Nagar' in x:
        return 'JP Nagar'
    elif 'Electronic City' in x:
        return 'Electronic City'
    elif 'Lakshminarayana' in x:
        return 'Lakshminarayana'
    elif 'Giri Nagar' in x:
        return 'Giri Nagar'
    elif 'Nagarbhavi' in x:
        return 'Nagarbhavi'
    elif 'Banashankari' in x:
        return 'Banashankari'
    elif 'HSR Layout' in x:
        return 'HSR Layout'
    elif 'Narayana Nagar' in x:
        return 'Narayana Nagar'
    elif 'Bagalur' in x:
        return 'Bagalur'
    elif 'BTM' in x:
        return 'BTM'
    else:
        return x

In [269]:
df['location'] = df['location'].apply(classify2)

In [270]:
df['location'].value_counts()

location
Whitefield                         541
Electronic City                    441
JP Nagar                           428
Sarjapur  Road                     399
Kanakpura Road                     273
                                  ...
Chuchangatta Colony                  1
Chikbasavanapura                     1
Sadhguru Layout                      1
beml layout, basaveshwara nagar      1
MM Layout                            1
Name: count, Length: 1244, dtype: int64

In [271]:
df['location'] = df['location'].str.replace('  ', ' ')

In [272]:
data = df['location'].value_counts()

In [273]:
data

location
Whitefield                         541
Electronic City                    441
JP Nagar                           428
Sarjapur Road                      399
Kanakpura Road                     273
                                  ...
Chuchangatta Colony                  1
Chikbasavanapura                     1
Sadhguru Layout                      1
beml layout, basaveshwara nagar      1
MM Layout                            1
Name: count, Length: 1244, dtype: int64

In [274]:
def classify3(x):
    if data[x] > 10:
        return x
    else:
        return 'Other'

In [275]:
df['location'] = df['location'].apply(classify3)

In [276]:
df['location'].unique()

array(['Electronic City', 'Chikka Tirupathi', 'Uttarahalli',
       'Lingadheeranahalli', 'Kothanur', 'Whitefield', 'Old Airport Road',
       'Rajaji Nagar', 'Marathahalli', 'Other', 'JP Nagar', 'Gottigere',
       'Sarjapur', 'Mysore Road', 'Bisuvanahalli',
       'Raja Rajeshwari Nagar', 'Kengeri', 'Binny Pete', 'Thanisandra',
       'Bellandur', 'Ramagondanahalli', 'Yelahanka', 'Hebbal',
       'Kasturi Nagar', 'Kanakpura Road', 'Electronics City Phase 1',
       'Kundalahalli', 'Chikkalasandra', 'Murugeshpalya', 'Sarjapur Road',
       'HSR Layout', 'Doddathoguru', 'KR Puram', 'Bhoganhalli',
       'Lakshminarayana', 'Begur Road', 'Devanahalli', 'Varthur',
       'Bommanahalli', 'Gunjur', 'Devarachikkanahalli', 'Hegde Nagar',
       'Haralur Road', 'Hennur Road', 'Kothannur', 'Kalena Agrahara',
       'Kaval Byrasandra', 'ISRO Layout', 'Garudachar Palya', 'EPIP Zone',
       'Dasanapura', 'Kasavanhalli', 'Sanjay nagar', 'Domlur',
       'Sarjapura - Attibele Road', 'Yeshwanthpur', 'Chandapura',
       'Nagarbhavi', 'Ramamurthy Nagar', 'Malleshwaram', 'Akshaya Nagar',
       'Shampura', 'Kadugodi', 'LB Shastri Nagar', 'Hormavu',
       'Vishwapriya Layout', 'Kudlu Gate', 'Bommasandra Industrial Area',
       'Anandapura', 'Vishveshwarya Layout', 'Kengeri Satellite Town',
       'Kannamangala', 'Hulimavu', 'Mahalakshmi Layout', 'Hosa Road',
       'Attibele', 'CV Raman Nagar', 'Kumaraswami Layout', 'Nagavara',
       'Hebbal Kempapura', 'Vijayanagar', 'Pattandur Agrahara',
       'Nagasandra', 'Kogilu', 'Panathur', 'Padmanabhanagar',
       '1st Block Jayanagar', 'Kammasandra', 'Dasarahalli', 'Magadi Road',
       'Koramangala', 'Dommasandra', 'Budigere', 'Kalyan nagar',
       'OMBR Layout', 'Horamavu Agara', 'Ambedkar Nagar',
       'Talaghattapura', 'Balagere', 'Jigani', 'Gollarapalya Hosahalli',
       'Old Madras Road', 'Kaggadasapura', 'Jakkur', 'TC Palaya',
       'Giri Nagar', 'Singasandra', 'AECS Layout', 'Mallasandra', 'Begur',
       'Malleshpalya', 'Munnekollal', 'Kaggalipura', 'Ulsoor',
       'Thigalarapalya', 'Somasundara Palya', 'Basaveshwara Nagar',
       'Bommasandra', 'Ardendale', 'Harlur', 'Banashankari', 'Kodihalli',
       'Narayanapura', 'Bannerghatta Road', 'Hennur', 'Kodigehaali',
       'Billekahalli', 'Jalahalli', 'Mahadevpura', 'Anekal', 'Sompura',
       'Dodda Nekkundi', 'Hosur Road', 'Battarahalli', 'Sultan Palaya',
       'Ambalipura', 'Hoodi', 'Brookefield', 'Yelenahalli', 'Vittasandra',
       'Vidyaranyapura', 'Amruthahalli', 'Kodigehalli', 'Subramanyapura',
       'Basavangudi', 'Kenchenahalli', 'Banjara Layout',
       'Kereguddadahalli', 'Kambipura', 'Rajiv Nagar', 'Arekere',
       'Mico Layout', 'Kammanahalli', 'Chikkabanavar', 'HRBR Layout',
       'Nehru Nagar', 'Kanakapura', 'Konanakunte', 'Margondanahalli',
       'R.T. Nagar', 'Tumkur Road', 'Vasanthapura', 'GM Palaya',
       'Jalahalli East', 'Hosakerehalli', 'Indira Nagar',
       'Kodichikkanahalli', 'Varthur Road', 'Anjanapura', 'Abbigere',
       'Tindlu', 'Gubbalala', 'Parappana Agrahara', 'Cunningham Road',
       'Kudlu', 'Cox Town', 'Kathriguppe', 'HBR Layout',
       'Yelahanka New Town', 'Sahakara Nagar', 'Rachenahalli',
       'Yelachenahalli', 'Green Glen Layout', 'Thubarahalli',
       'Horamavu Banaswadi', 'NGR Layout', 'Seegehalli', 'BEML Layout',
       'NRI Layout', 'ITPL', 'Babusapalaya', 'BTM', 'Iblur Village',
       'Ananth Nagar', 'Channasandra', 'Choodasandra', 'Kaikondrahalli',
       'Neeladri Nagar', 'Frazer Town', 'Cooke Town', 'Doddakallasandra',
       'Chamrajpet', 'Rayasandra', '5th Block Hbr Layout', 'Pai Layout',
       'Sonnenahalli', 'Benson Town', '2nd Phase Judicial Layout',
       'Poorna Pragna Layout', 'Judicial Layout', 'Karuna Nagar',
       'Bannerghatta', 'Marsur', 'Bommenahalli', 'Laggere',
       'Prithvi Layout', 'Banaswadi', 'Shivaji Nagar', 'Badavala Nagar',
       'Nagavarapalya', 'Hoskote', 'Doddaballapur', 'Sarakki Nagar',
       'Thyagaraja Nagar', 'Bharathi Nagar', 'HAL 2nd Stage',
       'Kadubeesanahalli'], dtype=object)

In [277]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [278]:
df['size']

0            2 BHK
1        4 Bedroom
2            3 BHK
3            3 BHK
4            2 BHK
           ...
13315    5 Bedroom
13316        4 BHK
13317        2 BHK
13318        4 BHK
13319        1 BHK
Name: size, Length: 13320, dtype: object

In [279]:
df['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [280]:
df['size'] = df['size'].str.replace('Bedroom', 'BHK')

In [281]:
df['size'].value_counts()

size
2 BHK     5528
3 BHK     4857
4 BHK     1417
1 BHK      643
5 BHK      356
6 BHK      221
7 BHK      100
8 BHK       89
9 BHK       54
10 BHK      14
1 RK        13
11 BHK       4
27 BHK       1
19 BHK       1
16 BHK       1
43 BHK       1
14 BHK       1
12 BHK       1
13 BHK       1
18 BHK       1
Name: count, dtype: int64

In [282]:
df['size'] = df['size'].fillna('2 BHK')

In [283]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [284]:
df['society']

0         Coomee
1        Theanmp
2            NaN
3        Soiewre
4            NaN
          ...
13315    ArsiaEx
13316        NaN
13317    Mahla T
13318    SollyCl
13319        NaN
Name: society, Length: 13320, dtype: object

In [285]:
df['society'].value_counts()

society
GrrvaGr    80
PrarePa    76
Prtates    59
Sryalan    59
GMown E    56
           ..
SNadeAr     1
DSellil     1
Shensit     1
VKvenas     1
Vemes H     1
Name: count, Length: 2688, dtype: int64

In [286]:
df.isnull().sum()

area_type          0
availability       0
location           0
size               0
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [287]:
df['society']

0         Coomee
1        Theanmp
2            NaN
3        Soiewre
4            NaN
          ...
13315    ArsiaEx
13316        NaN
13317    Mahla T
13318    SollyCl
13319        NaN
Name: society, Length: 13320, dtype: object

In [288]:
df = df.drop(columns = ['society'])

In [289]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super Built-Up Area,Under Construction,Electronic City,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready,Chikka Tirupathi,4 BHK,2600,5.0,3.0,120.00
2,Built-Up Area,Ready,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super Built-Up Area,Ready,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super Built-Up Area,Ready,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...
13315,Built-Up Area,Ready,Whitefield,5 BHK,3453,4.0,0.0,231.00
13316,Super Built-Up Area,Ready,Other,4 BHK,3600,5.0,NaN,400.00
13317,Built-Up Area,Ready,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Super Built-Up Area,Under Construction,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00
13319,Super Built-Up Area,Ready,Doddathoguru,1 BHK,550,1.0,1.0,17.00

In [290]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'total_sqft', 'bath',
       'balcony', 'price'],
      dtype='object')

In [291]:
df['total_sqft']

0        1056
1        2600
2        1440
3        1521
4        1200
         ...
13315    3453
13316    3600
13317    1141
13318    4689
13319     550
Name: total_sqft, Length: 13320, dtype: object

In [292]:
df['total_sqft'] = df['total_sqft'].astype('str')

In [293]:
def classify4(x):
    if '-' in x:
        for i in range(0, len(x)):
            if x[i] == '-':
                return x[0 : i - 1]
            else:
                continue
    else:
        return x

In [294]:
df['sqft1'] = df['total_sqft'].apply(classify4)

In [295]:
def classify5(x):
    if '-' in x:
        for i in range(0, len(x)):
            if x[i] == '-':
                return x[i + 2 : len(x)]
            else:
                continue
    else:
        return x

In [296]:
df['sqft2'] = df['total_sqft'].apply(classify5)

In [297]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price,sqft1,sqft2
0,Super Built-Up Area,Under Construction,Electronic City,2 BHK,1056,2.0,1.0,39.07,1056,1056
1,Plot Area,Ready,Chikka Tirupathi,4 BHK,2600,5.0,3.0,120.00,2600,2600
2,Built-Up Area,Ready,Uttarahalli,3 BHK,1440,2.0,3.0,62.00,1440,1440
3,Super Built-Up Area,Ready,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00,1521,1521
4,Super Built-Up Area,Ready,Kothanur,2 BHK,1200,2.0,1.0,51.00,1200,1200
...,...,...,...,...,...,...,...,...,...,...
13315,Built-Up Area,Ready,Whitefield,5 BHK,3453,4.0,0.0,231.00,3453,3453
13316,Super Built-Up Area,Ready,Other,4 BHK,3600,5.0,NaN,400.00,3600,3600
13317,Built-Up Area,Ready,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00,1141,1141
13318,Super Built-Up Area,Under Construction,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00,4689,4689
13319,Super Built-Up Area,Ready,Doddathoguru,1 BHK,550,1.0,1.0,17.00,550,550

In [298]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13320 non-null  object
 3   size          13320 non-null  object
 4   total_sqft    13320 non-null  object
 5   bath          13247 non-null  float64
 6   balcony       12711 non-null  float64
 7   price         13320 non-null  float64
 8   sqft1         13320 non-null  object
 9   sqft2         13320 non-null  object
dtypes: float64(3), object(7)
memory usage: 1.0+ MB

In [299]:
df['sqft1'].head(60)

0        1056
1        2600
2        1440
3        1521
4        1200
5        1170
6        2732
7        3300
8        1310
9        1020
10       1800
11       2785
12       1000
13       1100
14       2250
15       1175
16       1180
17       1540
18       2770
19       1100
20        600
21       1755
22       2800
23       1767
24        510
25       1250
26        660
27       1610
28       1151
29       1025
30       2100
31       1075
32       1760
33       1693
34       1925
35        700
36       1070
37       1724
38       1290
39       1143
40       1296
41       1254
42        600
43        660
44    1330.74
45        600
46        970
47       1459
48        800
49        869
50       1270
51       1670
52       2010
53       1185
54       1600
55       1200
56       3010
57       1500
58       1407
59        840
Name: sqft1, dtype: object

In [300]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13320 non-null  object
 3   size          13320 non-null  object
 4   total_sqft    13320 non-null  object
 5   bath          13247 non-null  float64
 6   balcony       12711 non-null  float64
 7   price         13320 non-null  float64
 8   sqft1         13320 non-null  object
 9   sqft2         13320 non-null  object
dtypes: float64(3), object(7)
memory usage: 1.0+ MB

In [301]:
#Sq. Yards (1 * 9)
#Sq. Meter (1 * 10.76)
#Acres (1 * 43560)
#Guntha (1 * 1089)
#Grounds (1 * 2400)
#Cents (1 * 435.6)

In [302]:
def calculation(x):
    for i in range(0, len(x)):
        if 'Yards' in x:
            if x[i] == 'S':
                return float(x[0 : i]) * 9
        elif 'Meter' in x: 
            if x[i] == 'S':
                return float(x[0 : i]) * 10.76
        elif 'Acres' in x:
            if x[i] == 'A':
                return float(x[0 : i]) * 43560
        elif 'Grounds' in x:
            if x[i] == 'G':
                return float(x[0 : i]) * 2400
        elif 'Guntha' in x:
            if x[i] == 'G':
                return float(x[0 : i]) * 1089
        elif 'Cents' in x:
            if x[i] == 'C':
                return float(x[0 : i]) * 435.6
        elif 'Perch' in x:
            if x[i] == 'P':
                return float(x[0 : i]) * 272.25
        else:
            return float(x)

In [303]:
df['sqft1'] = df['sqft1'].apply(calculation)

In [304]:
df['sqft1']

0        1056.0
1        2600.0
2        1440.0
3        1521.0
4        1200.0
          ...
13315    3453.0
13316    3600.0
13317    1141.0
13318    4689.0
13319     550.0
Name: sqft1, Length: 13320, dtype: float64

In [305]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13320 non-null  object
 3   size          13320 non-null  object
 4   total_sqft    13320 non-null  object
 5   bath          13247 non-null  float64
 6   balcony       12711 non-null  float64
 7   price         13320 non-null  float64
 8   sqft1         13320 non-null  float64
 9   sqft2         13320 non-null  object
dtypes: float64(4), object(6)
memory usage: 1.0+ MB

In [306]:
df['sqft2'] = df['sqft2'].astype('str')

In [307]:
df['sqft2'] = df['sqft2'].apply(calculation)

In [308]:
df['sqft2']

0        1056.0
1        2600.0
2        1440.0
3        1521.0
4        1200.0
          ...
13315    3453.0
13316    3600.0
13317    1141.0
13318    4689.0
13319     550.0
Name: sqft2, Length: 13320, dtype: float64

In [309]:
df['sqft2'].head(60)

0     1056.00
1     2600.00
2     1440.00
3     1521.00
4     1200.00
5     1170.00
6     2732.00
7     3300.00
8     1310.00
9     1020.00
10    1800.00
11    2785.00
12    1000.00
13    1100.00
14    2250.00
15    1175.00
16    1180.00
17    1540.00
18    2770.00
19    1100.00
20     600.00
21    1755.00
22    2800.00
23    1767.00
24     510.00
25    1250.00
26     660.00
27    1610.00
28    1151.00
29    1025.00
30    2850.00
31    1075.00
32    1760.00
33    1693.00
34    1925.00
35     700.00
36    1070.00
37    1724.00
38    1290.00
39    1143.00
40    1296.00
41    1254.00
42     600.00
43     660.00
44    1330.74
45     600.00
46     970.00
47    1459.00
48     800.00
49     869.00
50    1270.00
51    1670.00
52    2010.00
53    1185.00
54    1600.00
55    1200.00
56    3410.00
57    1500.00
58    1407.00
59     840.00
Name: sqft2, dtype: float64

In [310]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13320 non-null  object
 3   size          13320 non-null  object
 4   total_sqft    13320 non-null  object
 5   bath          13247 non-null  float64
 6   balcony       12711 non-null  float64
 7   price         13320 non-null  float64
 8   sqft1         13320 non-null  float64
 9   sqft2         13320 non-null  float64
dtypes: float64(5), object(5)
memory usage: 1.0+ MB

In [311]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price,sqft1,sqft2
0,Super Built-Up Area,Under Construction,Electronic City,2 BHK,1056,2.0,1.0,39.07,1056.0,1056.0
1,Plot Area,Ready,Chikka Tirupathi,4 BHK,2600,5.0,3.0,120.00,2600.0,2600.0
2,Built-Up Area,Ready,Uttarahalli,3 BHK,1440,2.0,3.0,62.00,1440.0,1440.0
3,Super Built-Up Area,Ready,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00,1521.0,1521.0
4,Super Built-Up Area,Ready,Kothanur,2 BHK,1200,2.0,1.0,51.00,1200.0,1200.0
...,...,...,...,...,...,...,...,...,...,...
13315,Built-Up Area,Ready,Whitefield,5 BHK,3453,4.0,0.0,231.00,3453.0,3453.0
13316,Super Built-Up Area,Ready,Other,4 BHK,3600,5.0,NaN,400.00,3600.0,3600.0
13317,Built-Up Area,Ready,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00,1141.0,1141.0
13318,Super Built-Up Area,Under Construction,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00,4689.0,4689.0
13319,Super Built-Up Area,Ready,Doddathoguru,1 BHK,550,1.0,1.0,17.00,550.0,550.0

In [312]:
df['total_sqft'] = (df['sqft1'] + df['sqft2']) / 2

In [313]:
df['total_sqft']

0        1056.0
1        2600.0
2        1440.0
3        1521.0
4        1200.0
          ...
13315    3453.0
13316    3600.0
13317    1141.0
13318    4689.0
13319     550.0
Name: total_sqft, Length: 13320, dtype: float64

In [314]:
df['total_sqft'].head(60)

0     1056.00
1     2600.00
2     1440.00
3     1521.00
4     1200.00
5     1170.00
6     2732.00
7     3300.00
8     1310.00
9     1020.00
10    1800.00
11    2785.00
12    1000.00
13    1100.00
14    2250.00
15    1175.00
16    1180.00
17    1540.00
18    2770.00
19    1100.00
20     600.00
21    1755.00
22    2800.00
23    1767.00
24     510.00
25    1250.00
26     660.00
27    1610.00
28    1151.00
29    1025.00
30    2475.00
31    1075.00
32    1760.00
33    1693.00
34    1925.00
35     700.00
36    1070.00
37    1724.00
38    1290.00
39    1143.00
40    1296.00
41    1254.00
42     600.00
43     660.00
44    1330.74
45     600.00
46     970.00
47    1459.00
48     800.00
49     869.00
50    1270.00
51    1670.00
52    2010.00
53    1185.00
54    1600.00
55    1200.00
56    3210.00
57    1500.00
58    1407.00
59     840.00
Name: total_sqft, dtype: float64

In [315]:
df.head(32)

,area_type,availability,location,size,total_sqft,bath,balcony,price,sqft1,sqft2
0,Super Built-Up Area,Under Construction,Electronic City,2 BHK,1056.0,2.0,1.0,39.07,1056.0,1056.0
1,Plot Area,Ready,Chikka Tirupathi,4 BHK,2600.0,5.0,3.0,120.00,2600.0,2600.0
2,Built-Up Area,Ready,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,1440.0,1440.0
3,Super Built-Up Area,Ready,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,1521.0,1521.0
4,Super Built-Up Area,Ready,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,1200.0,1200.0
5,Super Built-Up Area,Ready,Whitefield,2 BHK,1170.0,2.0,1.0,38.00,1170.0,1170.0
6,Super Built-Up Area,Under Construction,Old Airport Road,4 BHK,2732.0,4.0,NaN,204.00,2732.0,2732.0
7,Super Built-Up Area,Ready,Rajaji Nagar,4 BHK,3300.0,4.0,NaN,600.00,3300.0,3300.0
8,Super Built-Up Area,Ready,Marathahalli,3 BHK,1310.0,3.0,1.0,63.25,1310.0,1310.0
9,Plot Area,Ready,Other,6 BHK,1020.0,6.0,NaN,370.00,1020.0,1020.0
10,Super Built-Up Area,Under Construction,Whitefield,3 BHK,1800.0,2.0,2.0,70.00,1800.0,1800.0
11,Plot Area,Ready,Whitefield,4 BHK,2785.0,5.0,3.0,295.00,2785.0,2785.0
12,Super Built-Up Area,Ready,JP Nagar,2 BHK,1000.0,2.0,1.0,38.00,1000.0,1000.0
13,Built-Up Area,Ready,Gottigere,2 BHK,1100.0,2.0,2.0,40.00,1100.0,1100.0
14,Plot Area,Ready,Sarjapur,3 BHK,2250.0,3.0,2.0,148.00,2250.0,2250.0
15,Super Built-Up Area,Ready,Mysore Road,2 BHK,1175.0,2.0,2.0,73.50,1175.0,1175.0
16,Super Built-Up Area,Ready,Bisuvanahalli,3 BHK,1180.0,3.0,2.0,48.00,1180.0,1180.0
17,Super Built-Up Area,Ready,Raja Rajeshwari Nagar,3 BHK,1540.0,3.0,3.0,60.00,1540.0,1540.0
18,Super Built-Up Area,Ready,Other,3 BHK,2770.0,4.0,2.0,290.00,2770.0,2770.0
19,Super Built-Up Area,Ready,Other,2 BHK,1100.0,2.0,2.0,48.00,1100.0,1100.0
20,Built-Up Area,Ready,Kengeri,1 BHK,600.0,1.0,1.0,15.00,600.0,600.0
21,Super Built-Up Area,Under Construction,Binny Pete,3 BHK,1755.0,3.0,1.0,122.00,1755.0,1755.0
22,Plot Area,Ready,Thanisandra,4 BHK,2800.0,5.0,2.0,380.00,2800.0,2800.0
23,Super Built-Up Area,Ready,Bellandur,3 BHK,1767.0,3.0,1.0,103.00,1767.0,1767.0
24,Super Built-Up Area,Under Construction,Thanisandra,1 RK,510.0,1.0,0.0,25.25,510.0,510.0
25,Super Built-Up Area,Under Construction,Other,3 BHK,1250.0,3.0,2.0,56.00,1250.0,1250.0
26,Super Built-Up Area,Ready,Electronic City,2 BHK,660.0,1.0,1.0,23.10,660.0,660.0
27,Built-Up Area,Under Construction,Whitefield,3 BHK,1610.0,3.0,2.0,81.00,1610.0,1610.0
28,Super Built-Up Area,Under Construction,Ramagondanahalli,2 BHK,1151.0,2.0,2.0,48.77,1151.0,1151.0
29,Super Built-Up Area,Ready,Electronic City,3 BHK,1025.0,2.0,1.0,47.00,1025.0,1025.0
30,Super Built-Up Area,Under Construction,Yelahanka,4 BHK,2475.0,4.0,0.0,186.00,2100.0,2850.0
31,Super Built-Up Area,Ready,Bisuvanahalli,3 BHK,1075.0,2.0,1.0,35.00,1075.0,1075.0

In [316]:
np.median(df['bath'])

np.float64(nan)

In [317]:
data = df['bath']

In [318]:
df['bath'].value_counts()

bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64

In [319]:
df['bath'].unique()

array([ 2.,  5.,  3.,  4.,  6.,  1.,  9., nan,  8.,  7., 11., 10., 14.,
       27., 12., 16., 40., 15., 13., 18.])

In [320]:
df['bath'] = df['bath'].fillna(2.0)

In [321]:
df['bath'].unique()

array([ 2.,  5.,  3.,  4.,  6.,  1.,  9.,  8.,  7., 11., 10., 14., 27.,
       12., 16., 40., 15., 13., 18.])

In [322]:
df['bath'] = df['bath'].astype('int')

In [323]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13320 non-null  object
 3   size          13320 non-null  object
 4   total_sqft    13320 non-null  float64
 5   bath          13320 non-null  int64
 6   balcony       12711 non-null  float64
 7   price         13320 non-null  float64
 8   sqft1         13320 non-null  float64
 9   sqft2         13320 non-null  float64
dtypes: float64(5), int64(1), object(4)
memory usage: 1.0+ MB

In [324]:
df['bath']

0        2
1        5
2        2
3        3
4        2
        ..
13315    4
13316    5
13317    2
13318    4
13319    1
Name: bath, Length: 13320, dtype: int64

In [325]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'total_sqft', 'bath',
       'balcony', 'price', 'sqft1', 'sqft2'],
      dtype='object')

In [326]:
df['balcony']

0        1.0
1        3.0
2        3.0
3        1.0
4        1.0
        ...
13315    0.0
13316    NaN
13317    1.0
13318    1.0
13319    1.0
Name: balcony, Length: 13320, dtype: float64

In [327]:
df['balcony'].median()

2.0

In [328]:
data = df['balcony']

In [329]:
data[6661]

np.float64(2.0)

In [330]:
df['balcony'] = df['balcony'].fillna(2)

In [331]:
df['balcony'] = df['balcony'].astype('int')

In [332]:
df['balcony']

0        1
1        3
2        3
3        1
4        1
        ..
13315    0
13316    2
13317    1
13318    1
13319    1
Name: balcony, Length: 13320, dtype: int64

In [333]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13320 non-null  object
 3   size          13320 non-null  object
 4   total_sqft    13320 non-null  float64
 5   bath          13320 non-null  int64
 6   balcony       13320 non-null  int64
 7   price         13320 non-null  float64
 8   sqft1         13320 non-null  float64
 9   sqft2         13320 non-null  float64
dtypes: float64(4), int64(2), object(4)
memory usage: 1.0+ MB

In [334]:
df['price']

0         39.07
1        120.00
2         62.00
3         95.00
4         51.00
          ...
13315    231.00
13316    400.00
13317     60.00
13318    488.00
13319     17.00
Name: price, Length: 13320, dtype: float64

In [335]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13320 non-null  object
 3   size          13320 non-null  object
 4   total_sqft    13320 non-null  float64
 5   bath          13320 non-null  int64
 6   balcony       13320 non-null  int64
 7   price         13320 non-null  float64
 8   sqft1         13320 non-null  float64
 9   sqft2         13320 non-null  float64
dtypes: float64(4), int64(2), object(4)
memory usage: 1.0+ MB

In [336]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price,sqft1,sqft2
0,Super Built-Up Area,Under Construction,Electronic City,2 BHK,1056.0,2,1,39.07,1056.0,1056.0
1,Plot Area,Ready,Chikka Tirupathi,4 BHK,2600.0,5,3,120.00,2600.0,2600.0
2,Built-Up Area,Ready,Uttarahalli,3 BHK,1440.0,2,3,62.00,1440.0,1440.0
3,Super Built-Up Area,Ready,Lingadheeranahalli,3 BHK,1521.0,3,1,95.00,1521.0,1521.0
4,Super Built-Up Area,Ready,Kothanur,2 BHK,1200.0,2,1,51.00,1200.0,1200.0
...,...,...,...,...,...,...,...,...,...,...
13315,Built-Up Area,Ready,Whitefield,5 BHK,3453.0,4,0,231.00,3453.0,3453.0
13316,Super Built-Up Area,Ready,Other,4 BHK,3600.0,5,2,400.00,3600.0,3600.0
13317,Built-Up Area,Ready,Raja Rajeshwari Nagar,2 BHK,1141.0,2,1,60.00,1141.0,1141.0
13318,Super Built-Up Area,Under Construction,Padmanabhanagar,4 BHK,4689.0,4,1,488.00,4689.0,4689.0
13319,Super Built-Up Area,Ready,Doddathoguru,1 BHK,550.0,1,1,17.00,550.0,550.0

In [337]:
df.drop(columns = ['sqft1'], inplace = True)

In [339]:
df.drop(columns = ['sqft2'], inplace = True)

In [340]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super Built-Up Area,Under Construction,Electronic City,2 BHK,1056.0,2,1,39.07
1,Plot Area,Ready,Chikka Tirupathi,4 BHK,2600.0,5,3,120.00
2,Built-Up Area,Ready,Uttarahalli,3 BHK,1440.0,2,3,62.00
3,Super Built-Up Area,Ready,Lingadheeranahalli,3 BHK,1521.0,3,1,95.00
4,Super Built-Up Area,Ready,Kothanur,2 BHK,1200.0,2,1,51.00
...,...,...,...,...,...,...,...,...
13315,Built-Up Area,Ready,Whitefield,5 BHK,3453.0,4,0,231.00
13316,Super Built-Up Area,Ready,Other,4 BHK,3600.0,5,2,400.00
13317,Built-Up Area,Ready,Raja Rajeshwari Nagar,2 BHK,1141.0,2,1,60.00
13318,Super Built-Up Area,Under Construction,Padmanabhanagar,4 BHK,4689.0,4,1,488.00
13319,Super Built-Up Area,Ready,Doddathoguru,1 BHK,550.0,1,1,17.00